name: Go Test

on: [push, pull_request]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19'  # Use the version of Go in your project

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t logger-test .

      - name: Run Tests in Docker
        run: docker run --rm logger-test go test -v ./... -coverprofile=coverage.txt
